// server/models/Case.js
const mongoose = require('mongoose');

const CaseSchema = new mongoose.Schema({
  // FIXED: Changed from strict User ID to String Name for flexibility
  beneficiaryName: {
    type: String,
    required: [true, 'Please add the beneficiary name'],
    trim: true
  },
  
  // NEW FIELDS (Required for the simulation form)
  phone: {
    type: String,
    required: [true, 'Please add a phone number']
  },
  address: {
    type: String,
    required: [true, 'Please add an address']
  },

  title: {
    type: String, 
    required: [true, 'Please add a title (e.g., "Need Insulin")'],
    trim: true
  },
  
  type: { // Renamed from category to match frontend "type"
    type: String,
    enum: ['Medical', 'Education', 'Food', 'Shelter', 'Emergency', 'Housing'],
    required: true
  },
  
  description: {
    type: String,
    required: [true, 'Please describe your situation'],
    trim: true
  },
  
  // Document Vault (Optional for now)
  documents: [{
    docType: { type: String }, 
    url: { type: String }
  }],
  
  // Generated by the Algorithm (Renamed from urgencyScore to match Controller)
  priorityScore: {
    type: Number,
    default: 0,
    index: true 
  },
  
  // Governance
  status: {
    type: String,
    enum: ['Pending', 'Under Review', 'Approved', 'Rejected', 'Completed'],
    default: 'Pending'
  },
  
  // Link to the user who submitted/simulated it (Volunteer/Admin)
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, { timestamps: true });

module.exports = mongoose.model('Case', CaseSchema);