// server/controllers/userController.js
const User = require('../models/User');
const bcrypt = require('bcryptjs'); // Needed to verify/hash passwords

// @desc    Update user profile details
// @route   PUT /api/users/profile
// @access  Private (Logged in users)
exports.updateProfile = async (req, res) => {
  try {
    const { name, phone, city, area } = req.body;

    // Find the user by the ID in their secure token
    const user = await User.findById(req.user.id);
    if (!user) return res.status(404).json({ error: 'User not found' });

    // Update fields (Email is intentionally omitted)
    user.name = name || user.name;
    
    user.phone = phone || user.phone;
    
    user.city = city || user.city;
    user.area = area || user.area;

    const updatedUser = await user.save();

    res.status(200).json({ 
      success: true, 
      data: {
        id: updatedUser._id,
        name: updatedUser.name,
        email: updatedUser.email,
        role: updatedUser.role,
        
        phone: updatedUser.phone,
        
        city: updatedUser.city,
        area: updatedUser.area
      } 
    });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
};

// @desc    Update user password
// @route   PUT /api/users/password
// @access  Private
exports.updatePassword = async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;

    const user = await User.findById(req.user.id).select('+password');
    
    // 1. Verify current password
    const isMatch = await bcrypt.compare(currentPassword, user.password);
    if (!isMatch) {
      return res.status(401).json({ error: 'Current password is incorrect' });
    }

    // 2. THE FIX: Pass the raw text string directly to the user object.
    // Your server/models/User.js pre('save') hook will automatically intercept 
    // this and hash it exactly once before saving it to MongoDB.
    user.password = newPassword;
    
    await user.save();

    res.status(200).json({ success: true, message: 'Security key updated successfully' });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to update password' });
  }
};

// @desc    Upload profile photo
// @route   POST /api/users/upload-photo
// @access  Private
exports.uploadProfilePhoto = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No image file provided' });
    }

    const user = await User.findById(req.user.id);
    if (!user) return res.status(404).json({ error: 'User not found' });

    // Save the file path to the user's database record
    // req.file.filename is generated by multer below
    const imageUrl = `/uploads/${req.file.filename}`;
    user.profileImage = imageUrl; 
    await user.save();

    res.status(200).json({ success: true, imageUrl });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to upload image' });
  }
};

// @desc    Get current logged-in user profile
// @route   GET /api/users/profile
// @access  Private
exports.getProfile = async (req, res) => {
  try {
    // We use .select('-password') so we never accidentally send the password hash to the frontend
    const user = await User.findById(req.user.id).select('-password');
    if (!user) return res.status(404).json({ error: 'User not found' });
    
    res.status(200).json({ success: true, data: user });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to fetch profile' });
  }
};